package com.ruitx.babyboot.exceptions;

public class ErrorMessage {
    public static final String CLIENT_NOT_FOUND = "Client not found";
    public static final String CLIENT_ALREADY_EXIST = "Client already exist";
    public static final String CAR_NOT_FOUND = "Car not found";
    public static final String CAR_ALREADY_EXIST = "Car already exist";
    public static final String CAR_ALREADY_ON_RENTAL = "Car already on rental";

    public static final String RENTAL_NOT_FOUND = "Rental not found";
    public static final String RENTAL_ALREADY_EXIST = "Rental already exist";

    public static final String HANDLE_NOT_FOUND = "Handle not found";
    public static final String INVALID_ARGUMENT = "An invalid argument was provided";
    public static final String JSON_PARSING_ERROR = "An error occurred making the JSON response. Please try again later";
    public static final String GENERIC_ERROR = "An internal error occurred, please try again later";
}
